name: Ask Agent

on:
 workflow_dispatch:
   inputs:
     question:
       description: '问题'
       required: true
       type: string

jobs:
  create_thought_branch:
    runs-on: ubuntu-latest # 在最新的 Ubuntu runner 上运行
    outputs:
      start_commit: ${{ steps.create_branch.outputs.start_commit }}
      
    permissions:
      contents: write      # 需要读取并写入仓库内容

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_REPO_TOKEN }}
        
      - id: create_branch
        name: Push thought branch
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          timestamp=$(date +'%Y%m%d%H%M%S')
          rm chat
          mkdir chat
          mkdir "chat/user_${timestamp}"
          echo "${{github.event.inputs.question}}" > "chat/user_${timestamp}/message.md"
          git add chat
          git commit -m "thought question"
          git push origin ${{github.ref_name}}:ask-${{github.run_id}}
          echo "Create branch: [ask-${{github.run_id}}](${{ github.server_url }}/${{ github.repository }}/tree/ask-${{github.run_id}})" >> $GITHUB_STEP_SUMMARY
          echo "start_commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT


  branch_plan:
    runs-on: ubuntu-latest
    needs: create_thought_branch
    permissions:
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_REPO_TOKEN }}
          fetch-depth: 0
      - name: Read branch plan
        run: |

          for i in $(seq 1 60)
          do
            echo "--- 第 $i 次 ---"
            git pull        
            # 检查第一行是否为 "```"
            if head -n 1 README.md|grep '\`\`\`'; then
              cat README.md >> $GITHUB_STEP_SUMMARY
              exit 0 # 成功退出
            else
              echo "wait plan in README.md"
              sleep 5
            fi

          done        


        
  
