name: Agent Task by Issue 

on:
 issues:
    types: [opened]

jobs:
  create_thought_stack:
    runs-on: ubuntu-latest # 在最新的 Ubuntu runner 上运行
    container:
      image: ghcr.io/twwy/${{ github.event.repository.name }}/runtime-explorer:latest

    outputs:
      start_commit: ${{ steps.create_branch.outputs.start_commit }}
      
    permissions:
      contents: write      # 需要读取并写入仓库内容

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_REPO_TOKEN }}
      - id: create_branch
        name: Push thought branch
        run: |
          set -e
          ROOT_PATH=$(pwd)
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --global --add safe.directory ${ROOT_PATH}

          cat <<DELIMITER > /etc/gitops.yaml
          llm_model: qwen-max
          llm_api_url: https://dashscope.aliyuncs.com/compatible-mode/v1
          llm_api_key: ${{secrets.DASHSCOPE_API_KEY}}
          workspace_path: $(pwd)/workspace
          task_path: $(pwd)/task
          DELIMITER

          rm $(pwd)/workspace
          mkdir $(pwd)/workspace
          echo -e "${{ github.event.issue.title }}\n${{ github.event.issue.body }}" > "$(pwd)/workspace/input.md"

          python3 agent/explorer/explorer.agent.py ask

          git add .
          git commit -m "init stack"
          git push origin ${{github.ref_name}}:issue-${{ github.event.issue.number }}
          echo "Create branch: [issue-${{ github.event.issue.number }}](${{ github.server_url }}/${{ github.repository }}/tree/issue-${{ github.event.issue.number }}) [Actions](${{ github.server_url }}/${{ github.repository }}/actions?query=branch%3Aissue-${{ github.event.issue.number }})" >> $GITHUB_STEP_SUMMARY
      - uses: actions/github-script@v6
        id: create_comment
        with:
          github-token: ${{ secrets.GIT_REPO_TOKEN }}
          script: |
            const comment = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '已创建任务分支 [issue-${{ github.event.issue.number }}](${{ github.server_url }}/${{ github.repository }}/tree/issue-${{ github.event.issue.number }}) [Actions](${{ github.server_url }}/${{ github.repository }}/actions?query=branch%3Aissue-${{ github.event.issue.number }})'
            });
            console.log(comment);
