name: Planner

on:
 workflow_dispatch:
   inputs:
     test:
       description: 'test'
       required: false
       type: string

jobs:
  plan:
    runs-on: ubuntu-latest # 在最新的 Ubuntu runner 上运行
    container:
      image: ghcr.io/twwy/${{ github.event.repository.name }}/runtime-planner:latest

    permissions:
      contents: write      # 需要读取并写入仓库内容

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Push thought branch
        run: |

          set -e
          EXEC_BRANCH="${{github.ref_name}}"
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          
          cat <<DELIMITER > /etc/gitops.yaml
          llm_model: qwen-max
          llm_api_url: https://dashscope.aliyuncs.com/compatible-mode/v1
          llm_api_key: ${{secrets.DASHSCOPE_API_KEY}}
          work_root_path: $(pwd)
          DELIMITER
          
          python3 -m agitops.agent.planner
          git add .
          git commit -m "plan"
          
          if [ -f "task/doing-task" ]; then
            NEXT_TASK=$(cat task/doing-task)
            TARGET_BRANCH="${NEXT_TASK}/${EXEC_BRANCH}"
          else
            TARGET_BRANCH=${EXEC_BRANCH}
          fi

          echo "TARGET_BRANCH: ${TARGET_BRANCH}"          
          git push origin ${EXEC_BRANCH}:${TARGET_BRANCH}
