name: Agent Runtime Build

on:
 workflow_dispatch:
   inputs:
     agent:
       description: '智能体'
       required: false
       default: 'executor'
       type: choice
       options:
       - executor
       - planner

jobs:
  build-and-push:
    runs-on: ubuntu-latest # 在最新的 Ubuntu runner 上运行

    permissions:
      contents: read      # 需要读取仓库内容
      packages: write     # 需要写入 GitHub Packages (GHCR)
      # id-token: write  # 如果使用 OIDC 登录到云提供商的容器仓库，则可能需要

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # 检出你的代码

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # 或者 github.repository_owner
          password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN 自动由 GitHub Actions 提供

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./runtime/${{github.event.inputs.agent}}
          file: ./runtime/${{github.event.inputs.agent}}/Dockerfile
          tags: ghcr.io/${REPO}/runtime-${{github.event.inputs.agent}}:latest
