name: Docker Image CI

on:
 workflow_dispatch:
   inputs:
     agent:
       description: '智能体'
       required: false
       default: 'executor'
       type: choice
       options:
       - executor
       - planner

jobs:
  build-and-push:
    runs-on: ubuntu-latest # 在最新的 Ubuntu runner 上运行

    permissions:
      contents: read      # 需要读取仓库内容
      packages: write     # 需要写入 GitHub Packages (GHCR)
      # id-token: write  # 如果使用 OIDC 登录到云提供商的容器仓库，则可能需要

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # 检出你的代码

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      #   with:
      #     # 可选: 指定 buildx 版本
      #     # version: v0.10.0
      #     # 可选: 安装 buildkitd
      #     # install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # 或者 github.repository_owner
          password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN 自动由 GitHub Actions 提供

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./runtime/${{github.event.inputs.agent}}
          file: ./Dockerfile # Dockerfile 的路径
          tags: latest
          labels: ghcr.io/${{ github.repository_owner }}/runtime-${{github.event.inputs.agent}}-${{github.event.repository.id}}:${{ steps.meta.outputs.labels }}
          # platforms: linux/amd64,linux/arm64 # 可选: 构建多平台镜像
          # cache-from: type=gha # 可选: 启用 GitHub Actions 缓存
          # cache-to: type=gha,mode=max # 可选: 启用 GitHub Actions 缓存
